### ISSUE TITLE
IP reverse broken?

### ISSUE THREAD

**Issue by boomaker** [Sh4d1/scaleway-k8s-node-coffee#10]
Looks like the IP reverse feature is broken:

`could not update reverse on IP W.X.Y.Z for node scw-*****: scaleway-sdk-go: invalid argument(s): reverse does not respect constraint, Your reverse must resolve. Ensure the command 'dig +short Z.Y.X.W.*.fr' matches your IP address 'W.X.Y.Z'. If it does, please contact our support.`

Not sure since when, maybe the Scaleway API now enforce a reverse DNS record to be created?

**Comment by Sh4d1** [comment]
Hey :wave: indeed it should not be the case, could you open a Scaleway ticket about it? (Saying the reverse of the IP doesn't exists) As it's not really the scope of this project :smile:

**Comment by jtherin** [comment]
There was a bug allowing to set anything to the reverse (facebook.com, www.usa.gov...), now the legitimacy is verified.

**Comment by Sh4d1** [comment]
> indeed it should not be the case
Okay I thought the reverse was misisng for the Instance IP :sweat_smile: 

But yeah the only solution is to reserve and create the dns records before :/
