### ISSUE TITLE
If a node as already a reserved ip, the label should be present on node anyway

### ISSUE THREAD

**Issue by sogos** [Sh4d1/scaleway-k8s-node-coffee#6]
After an upgrade of k8s-node-coffee, i expected to see the label: `reserved-ip: true` 

The controller correctly see the reserved ip is assigned

```
I0409 09:52:59.422153 1 reserved_ip.go:18] adding a reserved IP on node scw-staging-staging-0cc9ecaafded4f819ffb839882
W0409 09:52:59.661995 1 reserved_ip.go:44] node scw-staging-staging-0cc9ecaafded4f819ffb839882 already have a public IP
```
But the label is not present :)

I can handle it manually would be great to fix ^^

**Comment by Sh4d1** [comment]
Hum that's weird, the message comes from here, and the label should be applied after 🤔 
https://github.com/Sh4d1/scaleway-k8s-node-coffee/blob/b7e9a9fcbea0725fb1824c980b16794fd965fe3f/pkg/controllers/reserved_ip.go#L44-L45
